/**
 * Project scaffolder -- generates configuration files and starter code.
 */

import { writeFile, mkdir } from 'node:fs/promises';
import { join } from 'node:path';
import { ADAPTERS } from './config.js';

export interface ScaffoldOptions {
  /** Target directory */
  directory: string;
  /** Selected adapter keys */
  adapters: string[];
  /** Collected config values */
  configValues: Record<string, Record<string, string | number | boolean>>;
  /** Project name */
  projectName: string;
}

/**
 * Scaffold a new project with selected adapters.
 */
export async function scaffoldProject(options: ScaffoldOptions): Promise<string[]> {
  const { directory, adapters, configValues, projectName } = options;
  const createdFiles: string[] = [];

  // Ensure directory exists
  await mkdir(directory, { recursive: true });
  await mkdir(join(directory, 'src'), { recursive: true });

  // Generate package.json
  const packageJson = generatePackageJson(projectName, adapters);
  const packageJsonPath = join(directory, 'package.json');
  await writeFile(packageJsonPath, JSON.stringify(packageJson, null, 2) + '\n');
  createdFiles.push('package.json');

  // Generate tsconfig.json
  const tsconfig = generateTsConfig();
  const tsconfigPath = join(directory, 'tsconfig.json');
  await writeFile(tsconfigPath, JSON.stringify(tsconfig, null, 2) + '\n');
  createdFiles.push('tsconfig.json');

  // Generate .env file
  const envContent = generateEnvFile(adapters, configValues);
  const envPath = join(directory, '.env');
  await writeFile(envPath, envContent);
  createdFiles.push('.env');

  // Generate .env.example
  const envExampleContent = generateEnvExample(adapters);
  const envExamplePath = join(directory, '.env.example');
  await writeFile(envExamplePath, envExampleContent);
  createdFiles.push('.env.example');

  // Generate .gitignore
  const gitignorePath = join(directory, '.gitignore');
  await writeFile(gitignorePath, GITIGNORE_CONTENT);
  createdFiles.push('.gitignore');

  // Generate main entry point
  const mainContent = generateMainFile(adapters);
  const mainPath = join(directory, 'src', 'index.ts');
  await writeFile(mainPath, mainContent);
  createdFiles.push('src/index.ts');

  // Generate README
  const readmeContent = generateReadme(projectName, adapters);
  const readmePath = join(directory, 'README.md');
  await writeFile(readmePath, readmeContent);
  createdFiles.push('README.md');

  // Generate Python files for hummingbot if selected
  if (adapters.includes('hummingbot')) {
    const reqPath = join(directory, 'requirements.txt');
    await writeFile(reqPath, 'deluthium-hummingbot>=0.1.0\n');
    createdFiles.push('requirements.txt');
  }

  return createdFiles;
}

function generatePackageJson(
  projectName: string,
  adapters: string[],
): Record<string, unknown> {
  const allDeps = new Set<string>();
  for (const key of adapters) {
    const info = ADAPTERS[key];
    if (info) {
      for (const dep of info.npmDependencies) {
        allDeps.add(dep);
      }
    }
  }

  const deps: Record<string, string> = {};
  for (const dep of allDeps) {
    if (dep.startsWith('@deluthium/')) {
      deps[dep] = '^0.1.0';
    } else if (dep === 'ethers') {
      deps[dep] = '^6.13.0';
    } else if (dep === 'ccxt') {
      deps[dep] = '^4.0.0';
    } else {
      deps[dep] = '*';
    }
  }

  // Always include dotenv
  deps['dotenv'] = '^16.4.0';

  return {
    name: projectName,
    version: '0.1.0',
    private: true,
    type: 'module',
    scripts: {
      start: 'node --import tsx src/index.ts',
      build: 'tsc -p tsconfig.json',
      dev: 'node --import tsx --watch src/index.ts',
    },
    dependencies: deps,
    devDependencies: {
      '@types/node': '^20.14.0',
      tsx: '^4.19.0',
      typescript: '^5.4.0',
    },
    engines: {
      node: '>=18.0.0',
    },
  };
}

function generateTsConfig(): Record<string, unknown> {
  return {
    compilerOptions: {
      target: 'ES2022',
      module: 'Node16',
      moduleResolution: 'Node16',
      lib: ['ES2022'],
      outDir: 'dist',
      rootDir: 'src',
      declaration: true,
      sourceMap: true,
      strict: true,
      esModuleInterop: true,
      skipLibCheck: true,
      forceConsistentCasingInFileNames: true,
      resolveJsonModule: true,
    },
    include: ['src'],
    exclude: ['node_modules', 'dist'],
  };
}

function generateEnvFile(
  adapters: string[],
  configValues: Record<string, Record<string, string | number | boolean>>,
): string {
  const lines: string[] = [
    '# Deluthium Connector Configuration',
    '# Generated by @deluthium/cli',
    '',
  ];

  for (const key of adapters) {
    const info = ADAPTERS[key];
    if (!info) continue;

    lines.push(`# --- ${info.label} ---`);
    const values = configValues[key] ?? {};

    for (const field of info.configFields) {
      const envKey = toEnvKey(key, field.key);
      const value = values[field.key] ?? field.default ?? '';
      lines.push(`${envKey}=${value}`);
    }
    lines.push('');
  }

  return lines.join('\n');
}

function generateEnvExample(adapters: string[]): string {
  const lines: string[] = [
    '# Deluthium Connector Configuration',
    '# Copy to .env and fill in your values',
    '',
  ];

  for (const key of adapters) {
    const info = ADAPTERS[key];
    if (!info) continue;

    lines.push(`# --- ${info.label} ---`);
    for (const field of info.configFields) {
      const envKey = toEnvKey(key, field.key);
      const placeholder = field.secret ? '<your-secret>' : String(field.default ?? '<value>');
      lines.push(`# ${field.description}`);
      lines.push(`${envKey}=${placeholder}`);
    }
    lines.push('');
  }

  return lines.join('\n');
}

function generateMainFile(adapters: string[]): string {
  const lines: string[] = [
    "import 'dotenv/config';",
    '',
  ];

  // Add imports
  for (const key of adapters) {
    const info = ADAPTERS[key];
    if (info && info.language !== 'python') {
      lines.push(info.importExample);
    }
  }

  lines.push('');
  lines.push('async function main() {');
  lines.push("  console.log('Deluthium Connector starting...\\n');");
  lines.push('');

  // Add initialization for each adapter
  for (const key of adapters) {
    const info = ADAPTERS[key];
    if (!info || info.language === 'python') continue;

    lines.push(`  // --- ${info.label} ---`);
    const indented = info.initExample.split('\n').map((line) => `  ${line}`).join('\n');
    lines.push(indented);
    lines.push('');
  }

  lines.push('}');
  lines.push('');
  lines.push('main().catch(console.error);');
  lines.push('');

  return lines.join('\n');
}

function generateReadme(projectName: string, adapters: string[]): string {
  const adapterList = adapters
    .map((key) => {
      const info = ADAPTERS[key];
      return info ? `- **${info.label}**: ${info.description}` : '';
    })
    .filter(Boolean)
    .join('\n');

  return `# ${projectName}

Built with [Deluthium Connector](https://github.com/deluthium-intern/deluthium-connector).

## Adapters

${adapterList}

## Setup

\`\`\`bash
# Install dependencies
npm install

# Copy env file and fill in your values
cp .env.example .env

# Run
npm start
\`\`\`

## Development

\`\`\`bash
# Watch mode
npm run dev

# Build
npm run build
\`\`\`
`;
}

function toEnvKey(adapter: string, field: string): string {
  const prefix = adapter.toUpperCase().replace(/-/g, '_');
  const suffix = field.replace(/([A-Z])/g, '_$1').toUpperCase();
  return `DELUTHIUM_${prefix}_${suffix}`;
}

const GITIGNORE_CONTENT = `node_modules/
dist/
.env
*.tsbuildinfo
.turbo/
`;
